#pragma once

#include <iostream>
#include <memory>
#include <utility>
#include <algorithm>
#include <functional>
#include <cassert>

#include <string>
#include <sstream>
#include <array>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <list>

#include "Core/Base.h"
#include "Core/Event.h"
#include "Core/Events.h"
#include "Core/TypeDef.h"
#include "Core/Factory.h"

#include "Memory/Memory.pch.inc"

#include "Graphics/Graphics.pch.inc"

#include "Platforms/Windows/Windows.pch.inc"
#include "Platforms/DirectX12/DX12.pch.inc"
